# Generated by Django 4.0.3 on 2022-04-04 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='firstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
