# Generated by Django 4.0.3 on 2022-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
