# Generated by Django 4.0.3 on 2022-04-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_userdetails_age_alter_userdetails_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultProfile.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('District', models.CharField(max_length=30, null=True)),
                ('Ward', models.CharField(max_length=30, null=True)),
                ('Details', models.TextField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
