# Generated by Django 4.0.3 on 2022-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userdetails_profile_pic_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='District',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Ward',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='date_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
