# Generated by Django 4.0.3 on 2022-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_address_district_remove_address_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='date_delivery',
            field=models.DateField(null=True),
        ),
    ]
