# Generated by Django 4.0.3 on 2022-05-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_confirmcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='confirmCode',
        ),
    ]
