# Generated by Django 4.0.3 on 2022-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_address_confirmcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('CardNumber', models.CharField(max_length=16, null=True)),
                ('ExpirationMonth', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('ExpirationYear', models.DecimalField(decimal_places=0, default=2022, max_digits=5)),
                ('SecurityCode', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
