# Generated by Django 4.0.3 on 2022-05-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_bill_address_remove_bill_payment_delete_favor'),
        ('account', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.bill'),
        ),
    ]
