# Generated by Django 4.0.3 on 2022-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_address_bill_alter_payment_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='SecurityCode',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
