# Generated by Django 4.0.3 on 2022-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_payment_securitycode_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='District',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
