# Generated by Django 4.0.3 on 2022-05-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_address_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='District',
            new_name='Ward',
        ),
    ]
