# Generated by Django 4.0.3 on 2022-04-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetails_age_alter_userdetails_firstname_and_more'),
        ('product', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ManyToManyField(to='product.tag')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userdetails')),
            ],
        ),
    ]
