# Generated by Django 4.0.3 on 2022-04-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_address_district_remove_address_ward_and_more'),
        ('product', '0005_remove_order_date_created_alter_order_quantity_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
    ]
