# Generated by Django 4.0.3 on 2022-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bill_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cofirmCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
