# Generated by Django 4.0.3 on 2022-04-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_bill_cofirmcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='cofirmCode',
            new_name='confirmCode',
        ),
    ]
