# Generated by Django 4.0.3 on 2022-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_bill_confirmcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='fullName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
