# Generated by Django 4.0.3 on 2022-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_tag_describe_tag_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
