# Generated by Django 4.0.3 on 2022-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
    ]
