# Generated by Django 4.0.3 on 2022-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_bill_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
