# Generated by Django 4.0.3 on 2022-04-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_bill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='confirmCode',
        ),
    ]
