# Generated by Django 4.0.3 on 2022-05-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_payment'),
        ('product', '0014_remove_bill_confirmcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='delivery',
        ),
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.payment'),
        ),
    ]
