# Generated by Django 4.0.3 on 2022-05-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_bill_date_created_remove_bill_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.DeleteModel(
            name='favor',
        ),
    ]
