# Generated by Django 4.0.3 on 2022-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_bill_address_remove_bill_payment_delete_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
