# Generated by Django 4.0.3 on 2022-05-07 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0017_bill_date_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('user', 'date_created')},
        ),
    ]
