# Generated by Django 4.0.3 on 2022-05-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_bill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
