# Generated by Django 4.0.3 on 2022-05-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tag'),
        ),
    ]
