# Generated by Django 4.0.3 on 2022-05-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_book_tag_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_confirmed',
        ),
    ]
