# Generated by Django 4.0.3 on 2022-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_bill_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
